global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.26.1:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.26.1:8080']
